### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by goto3** [gmaximov/StreamPlayer3#3]
Hello, download fails at 83% could you upload a zip?

I downloaded only the new StreamPlayer3 files and placed the old mpc-be and the chat didn't pop out :(

**Comment by gmaximov** [comment]
Try download mega folder as zip.

**Comment by gmaximov** [comment]
https://github.com/gmaximov/StreamPlayer3/releases/latest use this.

**Comment by goto3** [comment]
It downloads ok. Did you add the chat popout thing? it is not doing it to me. Using Windows 10 + Chrome

**Comment by gmaximov** [comment]
Yes, i did. But it is not working as it should yet.
